### ISSUE TITLE
WPSnapshots undefined variable s3_add ( and more )

### ISSUE THREAD

**Issue by JayWood** [10up/wp-local-docker-v2#41] opened 2019-09-11 13:48 UTC
**Describe the bug**
After updating to 2.5.1 I attempted to push a snapshot to AWS, however during the `Uploading files` transaction I'm greeted by 3 errors.

WP Local Docker v2 - 2.5.1
WPSnapshots - 1.5.1

**Steps to Reproduce**

1. `10updocker wpsnapshots push` ( configured to a repo which worked previously )

**Expected behavior**
Snapshot should successfully push to the internal repo.

**Screenshots**
https://gist.github.com/JayWood/204bf057e19c4948d8dae45f1d3b34a0

**Environment information**
 - Device: MacBook
 - OS: OSX Mojave 10.14.5
 - Browser and version: N/A
 - Plugins and version: Gutenberg, Restricted Site Access, Safe Redirect Manager, Safe SVG, Field Manager, Yoast ( all latest )
 - Theme and version: Custom Client Theme
 - Other installed plugin(s) and version(s): WordPress VIP MU-Plugins

**Additional context**
Doing a deeper dive into docker I removed all 10up/wpsnapshots images, I had both `:latest` and `:dev` figuring that would help. After running the command, `:dev` was re-downloaded. Which is apparently 8 months old ( give or take )?

This is apparently intentional to run `:dev` seeing as the snapshots command is running that image - https://github.com/10up/wp-local-docker-v2/blob/master/src/wpsnapshots.js#L62

I'm not entirely sure if this is VIP related only, so I'm going to try from another project later today and will report back.

**Comment by jeffpaul** [comment] 2019-09-11 14:08
@JayWood WP Snapshots latest version appears to be [v1.6](https://github.com/10up/wpsnapshots/releases/tag/1.6), are you able to test with that version and reproduce this issue as well?

**Comment by tylercherpak** [comment] 2021-12-15 01:30
Hey all, Closing this issue since there hasn't been a response in a while. Feel free to reopen if you are still having issues. Thanks!

**Closed by tylercherpak** 2021-12-15 01:30 UTC
Labels: type:bug
