### ISSUE TITLE
External access to server in WSL 2

### ISSUE THREAD

**Issue by matheusbronca** [10up/wp-local-docker-v2#163] opened 2020-11-05 13:02 UTC
Hi guys, how are you? I'm in trouble when attempting to connect to server from external devices, in my host  machine (windows) i can acess the server (created inside linux ubuntu in WSL 2) with no problem after i've added the configuration bellow in hosts file:

127.0.0.1 localdomain.test

After some research I found out that the windows iphelper (iphlpsvc) does not allow 10updocker containers to start, because iphelper uses ports 80 and 443 for tunneling, so whenever I have to start the containers i have to disable this service.
Is there any way to change the server ports so that i can keep the iphelper working? (I believe that the fact that I turn off this service prevents the network of my windows computer from being available on the network, consequently the WSL server too).

If anyone have suggestions or solutions, please reply this issue. 
(I'm sure there are other people with the same problem as me)
Thanks, have a great day! 🙌

**Comment by tylercherpak** [comment] 2021-12-16 01:43
Hey @matheusbronca even though this issue is actually older, I'm going to close it in favor of #184 since there is some good discussion going on there. 

Duplicate of #184

**Closed by tylercherpak** 2021-12-16 01:43 UTC
Labels: type:question
